// Helper script to patch ai.js in-place.
// Usage: node sanitizeFeatureScript_patch.js
//
// This patch replaces sanitizeFeatureScript() with an Option-2 “zero-issue gate” transformation
// engine that deterministically fixes common FeatureScript mistakes.

import fs from 'node:fs';
import path from 'node:path';

const filePath = path.join(process.cwd(), 'ai.js');
const src = fs.readFileSync(filePath, 'utf8');

const startMarker = 'function sanitizeFeatureScript(rawCode, opts = {})';
const start = src.indexOf(startMarker);
if (start === -1) throw new Error('sanitizeFeatureScript start not found');

const endMarker = '// ─── Dimension extractor';
const end = src.indexOf(endMarker, start);
if (end === -1) throw new Error('Dimension extractor marker not found');

// IMPORTANT:
// We build the replacement body as a normal JS string (not a template literal)
// and we aggressively escape any `${...}` sequences so Node never tries to interpolate them.

const replacement = [
  'function sanitizeFeatureScript(rawCode, opts = {}) {',
  '  const arrFixedIndexMap = opts.arrFixedIndexMap || {}; // optional mapping for known arrays',
  '  const changes = [];',
  '',
  '  let code = _coreFeatureScriptSanitize(rawCode);',
  '',
  '  function record(rule, before, after) {',
  '    if (typeof before !== "string" || typeof after !== "string") return;',
  '    changes.push({ rule, beforeSnippet: before.slice(0, 300), afterSnippet: after.slice(0, 300) });',
  '  }',
  '',
  '  // ========= Fatal catchers: loop/operator/array fixes =========',
  '',
  '  // Operator fixes: i++ / i-- (avoid FeatureScript parse errors)',
  '  {',
  '    const before = code;',
  '    code = code.replace(/\\b([A-Za-z_]\\w*)\\s*\\+\\+\\s*/g, "$1 += 1");',
  '    code = code.replace(/\\b([A-Za-z_]\\w*)\\s*--\\s*/g, "$1 -= 1");',
  '    if (code !== before) record("op_inc_dec_fix", before, code);',
  '  }',
  '',
  '  // Array length fix: replace arr.length with size(arr)',
  '  {',
  '    const before = code;',
  '    code = code.replace(/\\b([A-Za-z_]\\w*)\\.length\\b/g, "size($1)");',
  '    if (code !== before) record("array_length_to_size", before, code);',
  '  }',
  '',
  '  // Loop fix: const inside for/while blocks -> var (FeatureScript restriction)',
  '  try {',
  '    const loopStart = /\\b(for|while)\\s*\\(/;',
  '    if (loopStart.test(code)) {',
  '      code = code.replace(/(\\bfor\\s*\\([^)]*\\)\\s*\\{|\\bwhile\\s*\\([^)]*\\)\\s*\\{)([\\s\\S]*?)(\\n\\s*\\})/g, (m, open, inner, closing) => {',
  '        const fixedInner = inner.replace(/^([\\t ]*)const\\s+([A-Za-z_]\\w*)\\s*=\\s*/gm, "$1var $2 = ");',
  '        if (fixedInner !== inner) record("loop_const_to_var", inner, fixedInner);',
  '        return open + fixedInner + closing;',
  '      });',
  '    }',
  '  } catch {',
  '    // ignore',
  '  }',
  '',
  '  // ========= Constraint normalization: bounds specs & unit stripping =========',
  '',
  '  // Legacy numeric Default in isLength bounds: enforce LengthBoundSpec',
  '  {',
  '    const before = code;',
  '    code = code.replace(',
  '      /(annotation\\s*\\{\\s*"Name"\\s*:\\s*"[^"]+"\\s*),\\s*"Default"\\s*:\\s*"([0-9.]+)"\\s*\\*\\s*inch\\s*\\}\\s*\\n\\s*)isLength\\(\\s*definition\\.(\\w+)\\s*,\\s*(?:LENGTH_BOUNDS|NONNEGATIVE_ZERO_INCLUSIVE_LENGTH_BOUNDS)\\s*\\)\\s*;/g,',
  '      (match, annotationStart, defaultInches, paramName) => {',
  '        const def = Number(defaultInches);',
  '        const min = def <= 0 ? 0 : Math.min(0.01, Math.max(0, def * 0.1));',
  '        const max = Math.max(def * 10, min + 1);',
  '        const after = annotationStart + " }\\n        isLength(definition." + paramName + ", { (inch) : [" + n(min) + ", " + n(def) + ", " + n(max) + "] } as LengthBoundSpec);";',
  '        record("normalize_length_default_bounds", match, after);',
  '        return after;',
  '      }',
  '    );',
  '    if (code !== before) {}',
  '  }',
  '',
  '  // Normalize bounds-only isLength calls',
  '  {',
  '    code = code.replace(',
  '      /\\bisLength\\(\\s*definition\\.(\\w+)\\s*,\\s*(?:LENGTH_BOUNDS|NONNEGATIVE_ZERO_INCLUSIVE_LENGTH_BOUNDS)\\s*\\)\\s*;/g,',
  '      (match, paramName) => {',
  '        const after = "isLength(definition." + paramName + ", { (inch) : [0.01, 1.0, 100.0] } as LengthBoundSpec);";',
  '        record("normalize_length_bounds_constant", match, after);',
  '        return after;',
  '      }',
  '    );',
  '  }',
  '',
  '  // Ensure isLength(..., { (inch): [...] }) has as LengthBoundSpec',
  '  {',
  '    code = code.replace(',
  '      /\\bisLength\\(\\s*definition\\.(\\w+)\\s*,\\s*(\\{\\s*\\(inch\\)\\s*:\\s*\\[[^\\]]+\\]\\s*\\})\\s*\\)\\s*;/g,',
  '      (match, paramName, spec) => {',
  '        const after = "isLength(definition." + paramName + ", " + spec + " as LengthBoundSpec);";',
  '        record("add_length_bounds_spec_type", match, after);',
  '        return after;',
  '      }',
  '    );',
  '  }',
  '',
  '  // Unit stripping inside vector(...): definition.len -> (definition.len / inch) before * inch',
  '  {',
  '    code = code.replace(/vector\\s*\\(([^)]*\\bdefinition\\.\\w+[^)]*)\\)\\s*\\*\\s*inch/g, (match, args) => {',
  '      const fixedArgs = String(args).replace(/\\bdefinition\\.(\\w+)\\b(?!\\s*\\/\\s*inch)/g, "(definition.$1 / inch)");',
  '      const after = `vector(${fixedArgs}) * inch`;',
  '      if (after !== match) record("convert_length_params_inside_vector", match, after);',
  '      return after;',
  '    });',
  '  }',
  '',
  '  // ========= Skeleton enforcement: ensure sketches are solved & file ends properly =========',
  '',
  '  try {',
  '    const sketchCreateRegex = /(\\bvar\\s+([a-zA-Z0-9_$]+)\\s*=\\s*newSketch(?:OnPlane)?\\s*\\([^;]*\\);?)/g;',
  '    let sketchMatches = [];',
  '    let m;',
  '    while ((m = sketchCreateRegex.exec(code)) !== null) {',
  '      sketchMatches.push({ full: m[1], varName: m[2], index: m.index });',
  '    }',
  '    if (sketchMatches.length) {',
  '      sketchMatches.reverse();',
  '      for (const s of sketchMatches) {',
  '        const varName = s.varName;',
  '        const afterSketch = code.slice(s.index + s.full.length);',
  '        const hasSkSolve = new RegExp("skSolve\\\\s*\\\\(\\\\s*" + varName + "\\\\s*\\\\)").test(afterSketch);',
  '        const hasDownstreamOp = /(opExtrude|opRevolve|opLoft|opSweep)/.test(afterSketch);',
  '        if (hasDownstreamOp && !hasSkSolve) {',
  '          const insertion = "\\nskSolve(" + varName + ");\\n";',
  '          const insertPos = s.index + s.full.length;',
  '          code = code.slice(0, insertPos) + insertion + code.slice(insertPos);',
  '          record("insert_skSolve_after_sketch", s.full, insertion);',
  '        }',
  '      }',
  '    }',
  '  } catch {',
  '    // ignore',
  '  }',
  '',
  '  const trimmedCode = code.trimEnd();',
  '  if (/\\bdefineFeature\\s*\\(/.test(trimmedCode) && !trimmedCode.endsWith(";")) {',
  '    // Ensure defineFeature terminates with });',
  '    // (Best-effort: if missing, reconstruct minimal suffix by counting braces/parens)',
  '    let braceDepth = 0;',
  '    let parenDepth = 0;',
  '    for (let i = 0; i < trimmedCode.length; i++) {',
  '      const ch = trimmedCode[i];',
  '      if (ch === "{") braceDepth++;',
  '      else if (ch === "}") braceDepth--;',
  '      else if (ch === "(") parenDepth++;',
  '      else if (ch === ")") parenDepth--;',
  '    }',
  '    let suffix = "";',
  '    while (braceDepth > 0) { suffix += "\\n    }"; braceDepth--; }',
  '    while (parenDepth > 0) { suffix += ")"; parenDepth--; }',
  '    if (!suffix.endsWith(";")) suffix += ";";',
  '    if (suffix.length > 0) {',
  '      code = trimmedCode + suffix + "\\n";',
  '      record("fix_truncated_file_ending", "(truncated file)", suffix);',
  '    }',
  '  }',
  '',
  '  return { code, changes };',
  '}',
].join('\n');

const out = src.slice(0, start) + replacement + '\n\n' + src.slice(end);
fs.writeFileSync(filePath, out, 'utf8');
console.log('sanitizeFeatureScript patched successfully');

